import { describe, expect, it } from 'vitest';
import { TokenBucket } from './rateLimiter.js';

describe('TokenBucket', () => {
  it('allows removals up to the burst capacity', () => {
    const bucket = new TokenBucket(3, 0); // capacity 3, no refill
    expect(bucket.tryRemove(0)).toBe(true);
    expect(bucket.tryRemove(0)).toBe(true);
    expect(bucket.tryRemove(0)).toBe(true);
  });

  it('blocks once the bucket is exhausted', () => {
    const bucket = new TokenBucket(2, 0);
    expect(bucket.tryRemove(0)).toBe(true);
    expect(bucket.tryRemove(0)).toBe(true);
    expect(bucket.tryRemove(0)).toBe(false);
  });

  it('replenishes over time based on the refill rate', () => {
    // 1 token per 100ms.
    const bucket = new TokenBucket(1, 1 / 100);
    expect(bucket.tryRemove(0)).toBe(true);
    expect(bucket.tryRemove(0)).toBe(false);
    // Not enough time yet.
    expect(bucket.tryRemove(50)).toBe(false);
    // A full token has regenerated by t=100.
    expect(bucket.tryRemove(100)).toBe(true);
  });

  it('never accumulates beyond capacity', () => {
    const bucket = new TokenBucket(2, 1 / 100);
    // Idle for a long time — should still cap at 2.
    expect(bucket.tryRemove(10_000)).toBe(true);
    expect(bucket.tryRemove(10_000)).toBe(true);
    expect(bucket.tryRemove(10_000)).toBe(false);
  });

  it('supports removing multiple tokens at once', () => {
    const bucket = new TokenBucket(5, 0);
    expect(bucket.tryRemove(0, 5)).toBe(true);
    expect(bucket.tryRemove(0, 1)).toBe(false);
  });
});
